# fly.toml app configuration file generated for typepinyin on 2026-08-17T05:07:20Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'typepinyin'
primary_region = 'ams'

[http_service]
  auto_start_machines = true
  auto_stop_machines = true
  force_https = true
  internal_port = 8080
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory = '1gb'
  memory_mb = 256

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory = '512mb'
  memory_mb = 512
  processes = ['app']
  size = 'shared-cpu-1x'
